server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_REPOSITORY_URI}
          timeout: 3
          clone-on-start: true
          force-pull: true
          deleteUntrackedBranches: true
          default-label: ${CONFIG_SERVER_DEFAULT_LABEL:master}
  security:
    user:
      name: ${CONFIG_SERVER_USER:root}
      password: ${CONFIG_SERVER_PASSWORD:s3cr3t}
